name: Unity CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 👉 Kích hoạt license bằng username/password/serial
      - name: Activate Unity License
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 2022.3.5f1
          username: ${{ secrets.UNITY_EMAIL }}
          password: ${{ secrets.UNITY_PASSWORD }}
          serial: ${{ secrets.UNITY_SERIAL }}

      - name: Build Android
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.5f1
          targetPlatform: Android

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: Android-Build
          path: build/Android

      - name: Notify Telegram
        if: always() # báo về cả khi fail
        run: |
          STATUS="✅ Build *Android* (Unity 2022.3.5f1) thành công trên branch *${{ github.ref_name }}*"
          if [ "${{ job.status }}" != "success" ]; then STATUS="❌ Build Android thất bại trên branch *${{ github.ref_name }}*"; fi
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$STATUS" \
            -d parse_mode="Markdown"
